//! Windows resources for `fastpdf.exe` (spec §33, Explorer integration):
//!
//! - `ICON 1`: the application icon. ID 1 is also what GPUI loads for the
//!   window class (`LoadImageW(module, 1, IMAGE_ICON)`), so the title bar and
//!   taskbar use it too.
//! - `VERSIONINFO 1`: product name and version from Cargo (no company name).
//!
//! GPUI's `windows-manifest` feature already links `RT_MANIFEST #1` into the
//! binary through embed-resource. This script deliberately adds no manifest,
//! so the two resource files never contain the same (type, name) pair.
//! `assets/fastpdf.ico` is generated by `tools/icon/make_icon.py`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=assets/fastpdf.ico");
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    let Some(manifest_dir) = env::var_os("CARGO_MANIFEST_DIR").map(PathBuf::from) else {
        panic!("CARGO_MANIFEST_DIR is not set");
    };
    let Some(out_dir) = env::var_os("OUT_DIR").map(PathBuf::from) else {
        panic!("OUT_DIR is not set");
    };
    let icon = manifest_dir.join("assets").join("fastpdf.ico");
    if !icon.is_file() {
        panic!("missing {} (run tools/icon/make_icon.py)", icon.display());
    }

    let version = Version::from_env();
    let debug = env::var("PROFILE").as_deref() == Ok("debug");
    let rc = resource_script(&rc_path_literal(&icon), &version, debug);
    let rc_path = out_dir.join("fastpdf.rc");
    if let Err(e) = fs::write(&rc_path, rc) {
        panic!("cannot write {}: {e}", rc_path.display());
    }

    // Links the compiled .res into the `fastpdf` binary only (the crate has a
    // [[bin]] target, so embed-resource emits `rustc-link-arg-bins`).
    if let Err(e) = embed_resource::compile(&rc_path, embed_resource::NONE).manifest_optional() {
        panic!("compiling Windows resources failed: {e}");
    }
}

#[derive(Debug)]
struct Version {
    text: String,
    numbers: [u16; 4],
    prerelease: bool,
}

impl Version {
    fn from_env() -> Self {
        let part = |name: &str| -> u16 {
            let value = env::var(name).unwrap_or_default();
            match value.parse() {
                Ok(n) => n,
                Err(_) => panic!("{name}={value:?} does not fit a VERSIONINFO field (0..=65535)"),
            }
        };
        Self {
            text: env::var("CARGO_PKG_VERSION").unwrap_or_default(),
            numbers: [
                part("CARGO_PKG_VERSION_MAJOR"),
                part("CARGO_PKG_VERSION_MINOR"),
                part("CARGO_PKG_VERSION_PATCH"),
                0,
            ],
            prerelease: !env::var("CARGO_PKG_VERSION_PRE")
                .unwrap_or_default()
                .is_empty(),
        }
    }
}

/// Absolute path as an `.rc` string literal: forward slashes (no escape
/// sequences); the script is UTF-8 (`#pragma code_page(65001)`), so
/// non-ASCII directories work.
fn rc_path_literal(path: &std::path::Path) -> String {
    let text = path.to_string_lossy().replace('\\', "/");
    if text.contains('"') {
        panic!("unsupported character in path {text}");
    }
    format!("\"{text}\"")
}

fn rc_string(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\"\""))
}

fn resource_script(icon: &str, version: &Version, debug: bool) -> String {
    let [a, b, c, d] = version.numbers;
    let numeric = format!("{a},{b},{c},{d}");
    // VS_FF_DEBUG = 0x1, VS_FF_PRERELEASE = 0x2
    let flags = u32::from(debug) | (u32::from(version.prerelease) << 1);
    let text = rc_string(&version.text);
    format!(
        r#"#pragma code_page(65001)
// Generated by crates/fastpdf-app/build.rs. ICON and VERSIONINFO only:
// RT_MANIFEST #1 comes from GPUI's windows-manifest feature.

1 ICON {icon}

1 VERSIONINFO
FILEVERSION {numeric}
PRODUCTVERSION {numeric}
FILEFLAGSMASK 0x3F
FILEFLAGS 0x{flags:X}
FILEOS 0x40004
FILETYPE 0x1
FILESUBTYPE 0x0
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "FileDescription", "FastPDF"
            VALUE "FileVersion", {text}
            VALUE "InternalName", "fastpdf"
            VALUE "OriginalFilename", "fastpdf.exe"
            VALUE "ProductName", "FastPDF"
            VALUE "ProductVersion", {text}
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"#
    )
}
