//! Copy text (select all, then copy) on real text layers: generated
//! fixtures when present, and small synthetic documents for layouts the
//! corpus lacks (split lines, two columns, rotated text).

mod common;

use common::*;
use fastpdf_core::selection::{select_all, selected_text};
use fastpdf_engine_api::{CancelToken, EngineDocument, PageIndex, ResourceLimits, TextLayer};

/// The text layer of `page`. Test setup: a document that does not open
/// fails the test.
#[allow(clippy::expect_used)]
fn layer(bytes: Vec<u8>, page: u32) -> TextLayer {
    let doc = open_with(bytes, None, ResourceLimits::default()).expect("document opens");
    doc.text_layer(PageIndex::new(page), &CancelToken::new())
        .expect("text layer")
}

fn copy_all(layer: &TextLayer) -> String {
    selected_text(layer, &select_all(layer))
}

fn page(content: &str) -> PageSpec {
    PageSpec::new([0.0, 0.0, 612.0, 792.0], content)
}

/// One `BT … ET` line of 12 pt Helvetica at (x, y) in user space.
fn text(x: f64, y: f64, s: &str) -> String {
    format!("BT /F1 12 Tf {x} {y} Td ({s}) Tj ET\n")
}

/// A line drawn in two pieces, the second (left) piece last. "The quick"
/// is 52 pt wide in 12 pt Helvetica; a word space is 3.3 pt.
fn split_line_doc() -> Vec<u8> {
    let content = [
        text(127.5, 700.0, "brown fox"),
        text(72.0, 700.0, "The quick"),
        text(72.0, 685.0, "jumps over the dog"),
    ]
    .concat();
    build(&[page(&content)])
}

/// Two columns of three lines each, drawn column by column.
fn two_column_doc() -> Vec<u8> {
    let mut content = text(72.0, 740.0, "Two column heading");
    for (col, x) in [(1, 72.0), (2, 320.0)] {
        for line in 1..=3 {
            let y = 710.0 - 14.0 * f64::from(line);
            content.push_str(&text(x, y, &format!("column {col} line {line}")));
        }
    }
    build(&[page(&content)])
}

/// A landscape page made the usual way: portrait MediaBox, /Rotate 90 and
/// text drawn rotated by 90 degrees so that it reads upright on screen.
fn rotated_doc() -> Vec<u8> {
    let content = [
        "BT /F1 12 Tf 0 1 -1 0 100 72 Tm (First rotated line) Tj ET\n",
        "BT /F1 12 Tf 0 1 -1 0 115 72 Tm (second rotated line) Tj ET\n",
    ]
    .concat();
    let mut spec = page(&content);
    spec.rotate = Some(90);
    build(&[spec])
}

/// Letter spacing (Tc), word spacing (Tw) and a word gap made with TJ.
fn spacing_doc() -> Vec<u8> {
    let content = [
        "BT /F1 12 Tf 72 700 Td 2 Tc (Letter spaced) Tj 0 Tc ET\n",
        "BT /F1 12 Tf 72 680 Td 12 Tw (Word spacing applies) Tj 0 Tw ET\n",
        "BT /F1 12 Tf 72 660 Td [(Kerned) -350 (words)] TJ ET\n",
    ]
    .concat();
    build(&[page(&content)])
}

/// Two paragraphs: three lines 14 pt apart, a 28 pt gap, two lines.
fn paragraphs_doc() -> Vec<u8> {
    let mut content = String::new();
    for (i, y) in [700.0, 686.0, 672.0, 644.0, 630.0].into_iter().enumerate() {
        content.push_str(&text(72.0, y, &format!("paragraph line {}", i + 1)));
    }
    build(&[page(&content)])
}

#[test]
fn synthetic_layouts_copy_in_reading_order() {
    let cases: [(Vec<u8>, &str); 5] = [
        (split_line_doc(), "The quick brown fox\njumps over the dog"),
        (
            two_column_doc(),
            "Two column heading\n\n\
             column 1 line 1\ncolumn 1 line 2\ncolumn 1 line 3\n\
             column 2 line 1\ncolumn 2 line 2\ncolumn 2 line 3",
        ),
        (rotated_doc(), "First rotated line\nsecond rotated line"),
        (
            spacing_doc(),
            "Letter spaced\nWord spacing applies\nKerned words",
        ),
        (
            paragraphs_doc(),
            "paragraph line 1\nparagraph line 2\nparagraph line 3\n\n\
             paragraph line 4\nparagraph line 5",
        ),
    ];
    for (bytes, expected) in cases {
        assert_eq!(copy_all(&layer(bytes, 0)), expected);
    }
}

/// Reading order, spacing and breaks on the generated corpus (skipped when
/// the fixtures are not generated).
#[test]
fn generated_fixtures_copy_in_reading_order() {
    struct Case {
        file: &'static str,
        page: u32,
        starts: &'static str,
        contains: &'static [&'static str],
        ends: &'static str,
    }
    let cases = [
        Case {
            // The footer, drawn first, comes last.
            file: "small-text/three-pages-platypus-times.pdf",
            page: 0,
            starts: "FastPDF fixture: three pages (platypus)\n\n",
            contains: &[],
            ends: "transform;\n\nSynthetic text generated by tools/fixtures/generate.py \
                   (no third-party content).  Page 1",
        },
        Case {
            // Columns stay apart; the column change is a plain line break.
            file: "large-text/dense-300p-2col-helvetica.pdf",
            page: 0,
            starts: "FastPDF two-column fixture - page 1 of 300\n\n1.1.1 ",
            contains: &["\n1.1.3 Search of kerning body\n1.2.1 Scanline appendix next which\n\n"],
            ends: "",
        },
        Case {
            file: "traditional-chinese/gov-letter-embedded-ttfsubset.pdf",
            page: 0,
            starts: "【測試樣本】",
            contains: &[
                "\n檔　　號：\n保存年限：\n",
                "\n項次 檢測項目 檢測值 管制標準 判定\n1 粒狀污染物 58.2 mg/Nm3 50 mg/Nm3 不合格\n",
            ],
            ends: "\n第 1 頁",
        },
        Case {
            // The page number is the last line, not in the middle of the table.
            file: "traditional-chinese/lab-report-embedded-ttfsubset.pdf",
            page: 0,
            starts: "【測試樣本】",
            contains: &[
                "\nMCV 平均紅血球容積 79.2 L fL 80.0-100.0\nPLT 血小板 255 10^3/uL 150-400\n",
            ],
            ends: "\n病歷號碼 T000000001　第 1 頁",
        },
        Case {
            // Vertical writing: one line per column, right to left.
            file: "cjk/cid-nonembedded-vertical.pdf",
            page: 0,
            starts: "MSung-Light vertical writing (-UCS2-V CMap), right to left\n\
                     數字與單位：１２３４５、100公尺、3.5公斤、攝氏25度、NT$1,280元。數位\n\
                     轉型讓政府服務更加便利",
            contains: &[],
            ends: "",
        },
        Case {
            // No spaces between CJK characters a font switch apart.
            file: "cjk/cid-nonembedded-4lang.pdf",
            page: 0,
            starts: "",
            contains: &["焱、\n龘、倰齉、爨。\n"],
            ends: "",
        },
        Case {
            file: "fonts/text-state-operators.pdf",
            page: 0,
            starts: "",
            contains: &[
                "\nCharacter spacing 2 Tc\nWord spacing 12 Tw applies to spaces\n",
                "\nRise: base superscript subscript\n",
            ],
            ends: "",
        },
        Case {
            // A page inheriting /Rotate 90; its text is drawn unrotated.
            file: "large-page-count/balanced-tree-2000p.pdf",
            page: 1000,
            starts: "Page 1001 / 2000\n\ninherits /Rotate 90 from a level-2 node\n\
                     Page dictionary has no MediaBox/Resources of its own.",
            contains: &[],
            ends: "",
        },
    ];
    for case in cases {
        let Some(bytes) = fixture(case.file) else {
            continue;
        };
        let text = copy_all(&layer(bytes, case.page));
        let at = format!("{}#{}: {text:?}", case.file, case.page);
        assert!(text.starts_with(case.starts), "start of {at}");
        assert!(text.ends_with(case.ends), "end of {at}");
        for snippet in case.contains {
            assert!(text.contains(snippet), "{snippet:?} in {at}");
        }
        if case.file.contains("2col") {
            // No line holds text of both columns.
            assert!(text.lines().all(|l| l.chars().count() < 80), "{at}");
        }
    }
}

/// Generated fixtures and pages used for before/after comparisons.
const SNAPSHOT_FIXTURES: &[(&str, &[u32])] = &[
    ("small-text/one-page-helvetica.pdf", &[0]),
    ("small-text/three-pages-platypus-times.pdf", &[0, 1, 2]),
    ("small-text/two-pages-courier-letter.pdf", &[0, 1]),
    ("large-text/dense-300p-times.pdf", &[0]),
    ("large-text/dense-300p-2col-helvetica.pdf", &[0]),
    (
        "traditional-chinese/gov-letter-embedded-ttfsubset.pdf",
        &[0, 1, 2],
    ),
    (
        "traditional-chinese/gov-letter-cid-msung-nonembedded.pdf",
        &[0],
    ),
    (
        "traditional-chinese/lab-report-embedded-ttfsubset.pdf",
        &[0, 1],
    ),
    ("traditional-chinese/big5-level1-chars-ttfsubset.pdf", &[0]),
    ("cjk/cid-nonembedded-vertical.pdf", &[0]),
    ("cjk/cid-nonembedded-4lang.pdf", &[0]),
    ("japanese/embedded-ttfsubset.pdf", &[0]),
    ("fonts/text-state-operators.pdf", &[0]),
    ("large-page-count/balanced-tree-2000p.pdf", &[1000]),
    ("scanned/scan-gray-ocr-layer-5p.pdf", &[0]),
];

/// Writes the select-all copy text of the fixtures above and of the
/// synthetic documents to the file named by `$FASTPDF_COPY_SNAPSHOT`, to
/// compare copy text before and after a change.
#[test]
#[ignore = "measurement; run with --ignored --nocapture"]
fn copy_text_snapshot() {
    let Some(out) = std::env::var_os("FASTPDF_COPY_SNAPSHOT") else {
        return;
    };
    let mut report = String::new();
    let synthetic: [(&str, Vec<u8>); 5] = [
        ("synthetic/split-line", split_line_doc()),
        ("synthetic/two-column", two_column_doc()),
        ("synthetic/rotated-90", rotated_doc()),
        ("synthetic/spacing", spacing_doc()),
        ("synthetic/paragraphs", paragraphs_doc()),
    ];
    for (name, bytes) in synthetic {
        let text = copy_all(&layer(bytes, 0));
        report.push_str(&format!("===== {name}\n{text}\n"));
    }
    for (file, pages) in SNAPSHOT_FIXTURES {
        let Some(bytes) = fixture(file) else { continue };
        let doc = open_with(bytes, None, ResourceLimits::default()).unwrap();
        for &p in *pages {
            if p >= doc.page_count() {
                continue;
            }
            let layer = doc
                .text_layer(PageIndex::new(p), &CancelToken::new())
                .unwrap();
            report.push_str(&format!("===== {file}#{p}\n{}\n", copy_all(&layer)));
        }
    }
    std::fs::write(out, report).unwrap();
}
