"""Categories: small-text, large-text, large-page-count, fonts."""

from __future__ import annotations

import math
from pathlib import Path

from .common import Ctx, Job, latin_paragraph, latin_sentence, rng
from .rawpdf import (STD14, Content, RawPdf, Ref, info_dict, num, pdf_lit,
                     simple_document, std_font)
from .rl import A4, letter, rl_canvas, width_fn, wrap_text

LOREM_NOTE = "Synthetic text generated by tools/fixtures/generate.py (no third-party content)."


# --------------------------------------------------------------------------
# small-text
# --------------------------------------------------------------------------
def small_one_page(out: Path, ctx: Ctx) -> dict:
    r = rng("small-one-page")
    c = rl_canvas(out, "FastPDF fixture: one page Helvetica")
    W, H = A4
    y = H - 72
    c.setFont("Helvetica-Bold", 20)
    c.drawString(72, y, "FastPDF fixture: one page of plain text")
    y -= 34
    c.setFont("Helvetica", 10.5)
    done = False
    while not done:
        for line in wrap_text(latin_paragraph(r), "Helvetica", 10.5, W - 144):
            if y < 96:
                done = True
                break
            c.drawString(72, y, line)
            y -= 14
        y -= 8
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(72, 48, LOREM_NOTE)
    c.showPage()
    c.save()
    return {"pages": 1}


def small_three_pages_platypus(out: Path, ctx: Ctx) -> dict:
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib import colors
    from reportlab.platypus import (PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table,
                                    TableStyle, ListFlowable, ListItem)

    r = rng("small-three-pages")
    ss = getSampleStyleSheet()
    body = ss["BodyText"]
    body.fontName = "Times-Roman"
    body.fontSize = 11
    body.leading = 14

    def on_page(canvas, doc):
        n = canvas.getPageNumber()
        canvas.bookmarkPage(f"p{n}")
        canvas.addOutlineEntry(f"Page {n}", f"p{n}", level=0)
        canvas.setFont("Times-Italic", 8)
        canvas.drawString(72, 40, f"{LOREM_NOTE}  Page {n}")

    story = [Paragraph('<a name="intro"/>FastPDF fixture: three pages (platypus)', ss["Title"])]
    for _ in range(5):
        story.append(Paragraph(latin_paragraph(r, 4, 6), body))
    story.append(ListFlowable([ListItem(Paragraph(latin_sentence(r), body)) for _ in range(5)],
                              bulletType="bullet"))
    story.append(PageBreak())
    story.append(Paragraph("Section 2: a simple table", ss["Heading2"]))
    data = [["Metric", "Value", "Unit"]] + [
        [f"metric_{i:02d}", f"{r.uniform(0, 1000):.2f}", r.choice(["ms", "MB", "pages", "%"])]
        for i in range(14)]
    t = Table(data, colWidths=[160, 100, 80])
    t.setStyle(TableStyle([("FONT", (0, 0), (-1, -1), "Helvetica", 9),
                           ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
                           ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                           ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                           ("ALIGN", (1, 1), (1, -1), "RIGHT")]))
    story += [t, Spacer(1, 12)]
    for _ in range(3):
        story.append(Paragraph(latin_paragraph(r, 3, 5), body))
    story.append(PageBreak())
    story.append(Paragraph("Section 3: links", ss["Heading2"]))
    story.append(Paragraph('Internal link back to <a href="#intro" color="blue">the title</a>; '
                           'external link to <a href="https://example.com/fastpdf" color="blue">'
                           'example.com</a>.', body))
    for _ in range(4):
        story.append(Paragraph(latin_paragraph(r, 3, 5), body))

    doc = SimpleDocTemplate(str(out), pagesize=letter, title="FastPDF fixture: three pages",
                            author="FastPDF fixture generator (synthetic content)",
                            invariant=1)
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return {"pages": doc.page}


def small_two_pages_courier(out: Path, ctx: Ctx) -> dict:
    r = rng("small-two-pages-courier")
    c = rl_canvas(out, "FastPDF fixture: plain-text log, Courier", pagesize=letter)
    W, H = letter
    levels = ["INFO ", "DEBUG", "WARN ", "ERROR", "TRACE"]
    line_no = 0
    for page in range(2):
        c.setFont("Courier-Bold", 10)
        c.drawString(54, H - 54, f"fastpdf-bench.log  (synthetic)  page {page + 1}/2")
        c.setFont("Courier", 9)
        y = H - 74
        while y > 50:
            line_no += 1
            ms = line_no * 37 % 1000
            msg = " ".join(latin_sentence(r).split()[:9])
            c.drawString(54, y, f"2026-01-01T00:{line_no // 60 % 60:02d}:{line_no % 60:02d}.{ms:03d}"
                                f" {r.choice(levels)} {msg}"[:96])
            y -= 11
        c.showPage()
    c.save()
    return {"pages": 2}


# --------------------------------------------------------------------------
# large-text
# --------------------------------------------------------------------------
class _Words:
    """Endless stream of synthetic words, consumed one justified-width line at a time."""

    def __init__(self, r):
        self.r = r
        self.buf: list[str] = []
        self.pending: str | None = None

    def _next(self) -> str:
        if self.pending is not None:
            w, self.pending = self.pending, None
            return w
        if not self.buf:
            self.buf = latin_sentence(self.r).split()[::-1]
        return self.buf.pop()

    def line(self, wfn, space: float, max_w: float) -> str:
        cur: list[str] = []
        cur_w = 0.0
        while True:
            w = self._next()
            ww = wfn(w)
            if cur and cur_w + space + ww > max_w:
                self.pending = w
                return " ".join(cur)
            cur_w += (space if cur else 0.0) + ww
            cur.append(w)


def large_dense_times(out: Path, ctx: Ctx, pages: int = 300) -> dict:
    r = rng("large-dense-times")
    c = rl_canvas(out, f"FastPDF fixture: {pages} pages dense Times-Roman")
    W, H = A4
    font, size, leading = "Times-Roman", 9.0, 10.6
    wfn = width_fn(font, size)
    space = wfn(" ")
    words = _Words(r)
    max_w = W - 100
    for p in range(1, pages + 1):
        if (p - 1) % 10 == 0:
            ch = (p - 1) // 10 + 1
            c.bookmarkPage(f"ch{ch}")
            c.addOutlineEntry(f"Chapter {ch}", f"ch{ch}", level=0)
        c.setFont("Times-Bold", 11)
        c.drawString(50, H - 40, f"Chapter {(p - 1) // 10 + 1} - dense text page {p}")
        t = c.beginText(50, H - 58)
        t.setFont(font, size, leading)
        y = H - 58
        while y > 50:
            t.textLine(words.line(wfn, space, max_w))
            y -= leading
        c.drawText(t)
        c.setFont("Times-Italic", 7)
        c.drawCentredString(W / 2, 30, f"- {p} -")
        c.showPage()
    c.save()
    return {"pages": pages}


def large_dense_two_column(out: Path, ctx: Ctx, pages: int = 300) -> dict:
    r = rng("large-dense-2col")
    c = rl_canvas(out, f"FastPDF fixture: {pages} pages two-column Helvetica")
    W, H = A4
    font, size, leading = "Helvetica", 8.0, 9.6
    wfn = width_fn(font, size)
    space = wfn(" ")
    words = _Words(r)
    margin, gutter = 42.0, 18.0
    col_w = (W - 2 * margin - gutter) / 2
    heading_every = 38
    for p in range(1, pages + 1):
        c.setFont("Helvetica-Bold", 9)
        c.drawString(margin, H - 30, f"FastPDF two-column fixture - page {p} of {pages}")
        c.line(margin, H - 34, W - margin, H - 34)
        for col in range(2):
            x = margin + col * (col_w + gutter)
            y = H - 50
            n = 0
            while y > 44:
                n += 1
                if n % heading_every == 1:
                    c.setFont("Helvetica-Bold", 10)
                    c.drawString(x, y, f"{p}.{col + 1}.{n // heading_every + 1} "
                                       + " ".join(latin_sentence(r).split()[:4]).rstrip(".;?!:"))
                    y -= leading * 1.5
                    continue
                c.setFont(font, size)
                c.drawString(x, y, words.line(wfn, space, col_w))
                y -= leading
        c.showPage()
    c.save()
    return {"pages": pages}


# --------------------------------------------------------------------------
# large-page-count
# --------------------------------------------------------------------------
def pages_flat_reportlab(out: Path, ctx: Ctx, pages: int = 2000) -> dict:
    r = rng("pages-flat")
    c = rl_canvas(out, f"FastPDF fixture: {pages} simple pages (flat page tree)")
    W, H = A4
    for p in range(1, pages + 1):
        hue = (p * 37) % 360
        rr = 0.5 + 0.5 * math.cos(math.radians(hue))
        gg = 0.5 + 0.5 * math.cos(math.radians(hue - 120))
        bb = 0.5 + 0.5 * math.cos(math.radians(hue + 120))
        c.setFillColorRGB(rr, gg, bb)
        c.rect(60, H - 160, 60, 60, stroke=0, fill=1)
        c.setFillColorRGB(0, 0, 0)
        c.setFont("Helvetica-Bold", 40)
        c.drawString(140, H - 150, f"Page {p} / {pages}")
        c.setFont("Helvetica", 10)
        y = H - 200
        for line in wrap_text(latin_paragraph(r, 2, 3), "Helvetica", 10, W - 120)[:6]:
            c.drawString(60, y, line)
            y -= 13
        c.setFont("Helvetica", 8)
        c.drawCentredString(W / 2, 30, f"fixture page {p}")
        c.showPage()
    c.save()
    return {"pages": pages}


def _page_text_ops(lines: list[tuple[str, float, float, float, str]]) -> str:
    ops = []
    for font, size, x, y, text in lines:
        ops.append(f"BT /{font} {num(size)} Tf {num(x)} {num(y)} Td "
                   f"{pdf_lit(text.encode('cp1252', 'replace'))} Tj ET")
    return "\n".join(ops)


def pages_balanced_tree(out: Path, ctx: Ctx, pages: int = 2000, fan: int = 10) -> dict:
    """Balanced page tree with inherited MediaBox/CropBox/Rotate/Resources."""
    with open(out, "wb") as fp:
        pdf = RawPdf(fp, "1.7")
        f_helv = pdf.obj(std_font("Helvetica"))
        f_bold = pdf.obj(std_font("Helvetica-Bold"))
        f_times = pdf.obj(std_font("Times-Roman"))
        leaves = [pdf.alloc() for _ in range(pages)]
        levels = [leaves]
        while len(levels[-1]) > 1:
            prev = levels[-1]
            levels.append([pdf.alloc() for _ in range(math.ceil(len(prev) / fan))])
        parent: dict[int, Ref] = {}
        for li in range(len(levels) - 1):
            for i, ref in enumerate(levels[li]):
                parent[ref.num] = levels[li + 1][i // fan]
        # Inherited attribute overrides on selected intermediate nodes.
        overrides: dict[int, dict] = {
            levels[2][10].num: {"Rotate": 90},
            levels[2][15].num: {"MediaBox": [0, 0, 612, 792], "CropBox": [36, 36, 576, 756]},
            levels[1][0].num: {"Resources": {"Font": {"F1": f_times, "F2": f_bold}}},
        }

        def describe(i: int) -> str:
            n = i + 1
            if 1001 <= n <= 1100:
                return "inherits /Rotate 90 from a level-2 node"
            if 1501 <= n <= 1600:
                return "inherits Letter /MediaBox + /CropBox from a level-2 node"
            if n <= 10:
                return "inherits /Resources (Times-Roman as F1) from a level-1 node"
            return "inherits A4 /MediaBox and Helvetica /Resources from the root"

        for i, ref in enumerate(leaves):
            text = _page_text_ops([
                ("F2", 36, 60, 700, f"Page {i + 1} / {pages}"),
                ("F1", 12, 60, 660, describe(i)),
                ("F1", 10, 60, 640, "Page dictionary has no MediaBox/Resources of its own."),
            ])
            content = pdf.stream(text.encode("latin-1"))
            pdf.obj({"Type": "Page", "Parent": parent[ref.num], "Contents": content}, ref)
        for li in range(1, len(levels)):
            for i, ref in enumerate(levels[li]):
                kids = levels[li - 1][i * fan:(i + 1) * fan]
                count = min(pages, (i + 1) * fan ** li) - i * fan ** li
                d = {"Type": "Pages", "Kids": kids, "Count": count}
                if li < len(levels) - 1:
                    d["Parent"] = parent[ref.num]
                else:
                    d["MediaBox"] = [0, 0, 595.2756, 841.8898]
                    d["Resources"] = {"Font": {"F1": f_helv, "F2": f_bold},
                                      "ProcSet": ["PDF", "Text"]}
                d.update(overrides.get(ref.num, {}))
                pdf.obj(d, ref)
        root = pdf.obj({"Type": "Catalog", "Pages": levels[-1][0], "PageLayout": "SinglePage"})
        info = pdf.obj(info_dict(f"FastPDF fixture: {pages} pages, balanced page tree"))
        pdf.finish(root, info, id_seed="pages-balanced-tree")
    return {"pages": pages}


def pages_objstm(out: Path, ctx: Ctx, pages: int = 2000, fan: int = 50) -> dict:
    """PDF 1.5 file: page dicts in object streams, cross-reference stream."""
    sizes = [(595.2756, 841.8898), (612, 792), (419.5276, 595.2756), (1190.5512, 841.8898)]
    with open(out, "wb") as fp:
        pdf = RawPdf(fp, "1.5", objstm_size=100)
        f1 = pdf.objstm_obj(std_font("Helvetica"))
        f2 = pdf.objstm_obj(std_font("Courier-Bold"))
        root_pages = pdf.alloc()
        groups = [pdf.alloc() for _ in range(math.ceil(pages / fan))]
        for gi, gref in enumerate(groups):
            kids = []
            for i in range(gi * fan, min(pages, (gi + 1) * fan)):
                w, h = sizes[i % len(sizes)]
                text = _page_text_ops([
                    ("F2", 28, 40, h - 80, f"Page {i + 1} / {pages}"),
                    ("F1", 11, 40, h - 110, f"Object-stream page, size {num(w)} x {num(h)} pt"),
                ])
                content = pdf.stream(text.encode("latin-1"))
                kids.append(pdf.objstm_obj({"Type": "Page", "Parent": gref,
                                            "MediaBox": [0, 0, w, h], "Contents": content}))
            pdf.objstm_obj({"Type": "Pages", "Parent": root_pages, "Kids": kids,
                            "Count": len(kids)}, gref)
        pdf.objstm_obj({"Type": "Pages", "Kids": groups, "Count": pages,
                        "Resources": {"Font": {"F1": f1, "F2": f2}}}, root_pages)
        root = pdf.objstm_obj({"Type": "Catalog", "Pages": root_pages})
        info = pdf.objstm_obj(info_dict(f"FastPDF fixture: {pages} pages in object streams"))
        pdf.finish(root, info, id_seed="pages-objstm", xref_stream=True)
    return {"pages": pages}


# --------------------------------------------------------------------------
# fonts
# --------------------------------------------------------------------------
SAMPLE_LATIN = ("The quick brown fox jumps over the lazy dog 0123456789 "
                "ÀÉÎÕÜ àéîõü ß Ææ "
                "Øø ‰ € “quotes” – —")


def fonts_standard14(out: Path, ctx: Ctx) -> dict:
    """All 14 standard fonts (non-embedded) plus code tables and encodings."""
    with open(out, "wb") as fp:
        pdf = RawPdf(fp, "1.7")
        fonts = {f"S{i}": pdf.obj(std_font(base)) for i, base in enumerate(STD14)}
        fonts["MR"] = pdf.obj(std_font("Helvetica", "MacRomanEncoding"))
        fonts["BI"] = pdf.obj({"Type": "Font", "Subtype": "Type1", "BaseFont": "Helvetica"})
        diffs = [128, "Lslash", "lslash", "Scaron", "scaron", "Zcaron", "zcaron", "OE", "oe",
                 "fi", "fl", "dotlessi", "florin", "fraction", "breve", "ogonek", "caron"]
        fonts["DF"] = pdf.obj({"Type": "Font", "Subtype": "Type1", "BaseFont": "Helvetica",
                               "Encoding": {"Type": "Encoding", "BaseEncoding": "WinAnsiEncoding",
                                            "Differences": diffs}})
        res = {"Font": fonts, "ProcSet": ["PDF", "Text"]}
        pages_ref = pdf.alloc()
        page_refs = []
        W, H = 595.2756, 841.8898

        def add_page(cs: Content) -> None:
            content = pdf.stream(cs.data())
            page_refs.append(pdf.obj({"Type": "Page", "Parent": pages_ref, "MediaBox": [0, 0, W, H],
                                      "Resources": res, "Contents": content}))

        # Page 1: every standard font
        cs = Content()
        cs(f"BT /S5 16 Tf 50 {num(H - 50)} Td (The 14 standard Type 1 fonts \\(not embedded\\)) Tj ET")
        y = H - 90
        for i, base in enumerate(STD14):
            cs(f"BT /S4 8 Tf 50 {num(y + 14)} Td {pdf_lit(base.encode())} Tj ET")
            if base == "Symbol":
                sample = b"abgdezhqiklmnxoprstufcyw ABGDEZHQIKLMNXOPRSTUFCYW \xa5\xa3\xb3\xc5\xc4"
            elif base == "ZapfDingbats":
                sample = bytes(range(0x21, 0x50))
            else:
                sample = SAMPLE_LATIN.encode("cp1252")
            cs(f"BT /S{i} 13 Tf 50 {num(y)} Td {pdf_lit(sample)} Tj ET")
            y -= 52
        add_page(cs)

        # Pages 2-4: code tables
        for title, res_name in (("Times-Roman / WinAnsiEncoding", "S0"),
                                ("Symbol / built-in encoding", "S12"),
                                ("ZapfDingbats / built-in encoding", "S13"),
                                ("Helvetica / built-in StandardEncoding (no /Encoding)", "BI")):
            cs = Content()
            cs(f"BT /S5 14 Tf 50 {num(H - 50)} Td {pdf_lit(title.encode())} Tj ET")
            cs("0.6 G 0.3 w")
            for code in range(0x20, 0x100):
                row, col = divmod(code - 0x20, 16)
                x = 50 + col * 31
                y = H - 100 - row * 50
                cs(f"{num(x)} {num(y - 8)} 29 40 re S")
                cs(f"BT /S4 5 Tf {num(x + 2)} {num(y + 25)} Td ({code:02X}) Tj ET")
                cs(f"BT /{res_name} 16 Tf {num(x + 7)} {num(y)} Td {pdf_lit(bytes([code]))} Tj ET")
            add_page(cs)

        # Page 5: other encodings
        cs = Content()
        cs(f"BT /S5 14 Tf 50 {num(H - 50)} Td (Encodings: MacRoman and /Differences) Tj ET")
        mac = "Mac Roman: ÄÅÇÉÑÖÜáàâ †°¢£§•¶ß®©™"
        cs(f"BT /MR 14 Tf 50 {num(H - 100)} Td {pdf_lit(mac.encode('mac_roman'))} Tj ET")
        cs(f"BT /DF 14 Tf 50 {num(H - 140)} Td (Differences 128-143: ) Tj "
           f"{pdf_lit(bytes(range(128, 144)))} Tj ET")
        add_page(cs)

        simple_document(pdf, page_refs, pages_ref, title="FastPDF fixture: standard 14 fonts",
                        id_seed="fonts-standard14")
    return {"pages": len(page_refs)}


def fonts_truetype_vera(out: Path, ctx: Ctx) -> dict:
    import reportlab
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    fdir = Path(reportlab.__file__).parent / "fonts"
    for name, file in (("Vera", "Vera.ttf"), ("VeraBd", "VeraBd.ttf"),
                       ("VeraIt", "VeraIt.ttf"), ("VeraBI", "VeraBI.ttf")):
        pdfmetrics.registerFont(TTFont(name, str(fdir / file)))
    r = rng("fonts-vera")
    c = rl_canvas(out, "FastPDF fixture: embedded TrueType subsets (Bitstream Vera)")
    W, H = A4
    pages = 0
    for face in ("Vera", "VeraBd", "VeraIt", "VeraBI"):
        y = H - 60
        c.setFont(face, 18)
        c.drawString(56, y, f"{face}: embedded TrueType subset")
        y -= 30
        c.setFont(face, 12)
        c.drawString(56, y, SAMPLE_LATIN.replace("€", "EUR").replace("‰", "%o"))
        y -= 20
        # every printable Latin-1 character
        chars = "".join(chr(i) for i in range(0x21, 0x7F)) + "".join(chr(i) for i in range(0xA1, 0x100))
        for i in range(0, len(chars), 48):
            c.drawString(56, y, " ".join(chars[i:i + 48]))
            y -= 18
        c.setFont(face, 10)
        y -= 10
        while y > 60:
            for line in wrap_text(latin_paragraph(r), face, 10, W - 112):
                if y < 60:
                    break
                c.drawString(56, y, line)
                y -= 13
            y -= 6
        c.showPage()
        pages += 1
    c.save()
    return {"pages": pages}


def fonts_type1_embedded(out: Path, ctx: Ctx) -> dict:
    import reportlab
    from reportlab.pdfbase import pdfmetrics

    fdir = Path(reportlab.__file__).parent / "fonts"
    face = pdfmetrics.EmbeddedType1Face(str(fdir / "callig15.afm"), str(fdir / "callig15.pfb"))
    pdfmetrics.registerTypeFace(face)
    pdfmetrics.registerFont(pdfmetrics.Font("Callig15", face.name, "WinAnsiEncoding"))
    r = rng("fonts-type1")
    c = rl_canvas(out, "FastPDF fixture: embedded Type 1 font (callig15)")
    W, H = A4
    y = H - 70
    c.setFont("Helvetica-Bold", 14)
    c.drawString(56, y, "Embedded Type 1 (FontFile) - callig15 by P. Vanroose / S. Dachian")
    y -= 40
    for size in (36, 24, 16):
        c.setFont("Callig15", size)
        c.drawString(56, y, "The quick brown fox jumps over the lazy dog")
        y -= size * 1.6
    c.setFont("Callig15", 13)
    while y > 70:
        for line in wrap_text(latin_paragraph(r), "Callig15", 13, W - 112):
            if y < 70:
                break
            c.drawString(56, y, line)
            y -= 18
    c.showPage()
    c.save()
    return {"pages": 1}


# Type3 fonts --------------------------------------------------------------
_SEG = {"a": [(0, 1000), (600, 1000)], "b": [(600, 1000), (600, 500)],
        "c": [(600, 500), (600, 0)], "d": [(0, 0), (600, 0)], "e": [(0, 0), (0, 500)],
        "f": [(0, 500), (0, 1000)], "g": [(0, 500), (600, 500)]}
_DIGITS = ["abcdef", "bc", "abged", "abgcd", "fgbc", "afgcd", "afgedc", "abc", "abcdefg", "abcdfg"]
_STROKE_LETTERS = {
    "A": [[(0, 0), (300, 1000), (600, 0)], [(110, 370), (490, 370)]],
    "D": [[(0, 0), (0, 1000), (400, 1000), (600, 800), (600, 200), (400, 0), (0, 0)]],
    "E": [[(600, 0), (0, 0), (0, 1000), (600, 1000)], [(0, 500), (450, 500)]],
    "F": [[(0, 0), (0, 1000), (600, 1000)], [(0, 500), (450, 500)]],
    "K": [[(0, 0), (0, 1000)], [(600, 1000), (0, 420)], [(210, 620), (600, 0)]],
    "N": [[(0, 0), (0, 1000), (600, 0), (600, 1000)]],
    "O": [[(0, 0), (600, 0), (600, 1000), (0, 1000), (0, 0)]],
    "P": [[(0, 0), (0, 1000), (500, 1000), (600, 900), (600, 600), (500, 500), (0, 500)]],
    "R": [[(0, 0), (0, 1000), (500, 1000), (600, 900), (600, 600), (500, 500), (0, 500)],
          [(250, 500), (600, 0)]],
    "S": [[(600, 900), (500, 1000), (100, 1000), (0, 900), (0, 600), (100, 500), (500, 500),
           (600, 400), (600, 100), (500, 0), (100, 0), (0, 100)]],
    "T": [[(0, 1000), (600, 1000)], [(300, 1000), (300, 0)]],
    "Y": [[(0, 1000), (300, 500), (600, 1000)], [(300, 500), (300, 0)]],
}


def _stroke_glyph(paths) -> bytes:
    ops = ["800 0 -60 -60 660 1060 d1", "70 w 1 J 1 j"]
    for path in paths:
        (x0, y0), rest = path[0], path[1:]
        ops.append(f"{x0} {y0} m " + " ".join(f"{x} {y} l" for x, y in rest) + " S")
    return "\n".join(ops).encode("ascii")


def _bitmap_font(pdf: RawPdf) -> tuple[Ref, dict[str, float]]:
    """dvips/pdfTeX-style Type3 font whose glyphs are 1-bit inline image masks."""
    from PIL import Image, ImageDraw, ImageFont

    px = 48
    unit = 1000.0 / px
    font = ImageFont.load_default(size=px)
    procs: dict[str, Ref] = {}
    widths: list[float] = []
    adv: dict[str, float] = {}
    diffs: list = [32]
    for code in range(32, 127):
        ch = chr(code)
        gname = f"g{code}"
        diffs.append(gname)
        w_units = round(font.getlength(ch) * unit)
        widths.append(w_units)
        adv[ch] = w_units / 1000.0
        l, t, r_, b = font.getbbox(ch, anchor="ls")
        if r_ <= l or b <= t:
            body = f"{w_units} 0 0 0 0 0 d1".encode("ascii")
        else:
            w, h = r_ - l, b - t
            img = Image.new("1", (w, h), 0)
            ImageDraw.Draw(img).text((-l, -t), ch, font=font, fill=1, anchor="ls")
            data = img.tobytes()
            llx, lly = round(l * unit), round(-b * unit)
            urx, ury = round(r_ * unit), round(-t * unit)
            head = (f"{w_units} 0 {llx} {lly} {urx} {ury} d1\nq {urx - llx} 0 0 {ury - lly} "
                    f"{llx} {lly} cm\nBI /IM true /W {w} /H {h} /BPC 1 /D [1 0]")
            if b"EI" in data:
                body = (head + f" /F /AHx ID {data.hex()}> EI Q").encode("ascii")
            else:
                body = head.encode("ascii") + b" ID " + data + b"\nEI Q"
        procs[gname] = pdf.stream(body, compress=False)
    ref = pdf.obj({"Type": "Font", "Subtype": "Type3", "FontBBox": [-200, -300, 1200, 1100],
                   "FontMatrix": [0.001, 0, 0, 0.001, 0, 0], "CharProcs": procs,
                   "Encoding": {"Type": "Encoding", "Differences": diffs},
                   "FirstChar": 32, "LastChar": 126, "Widths": widths, "Resources": {}})
    return ref, adv


def fonts_type3(out: Path, ctx: Ctx) -> dict:
    r = rng("fonts-type3")
    with open(out, "wb") as fp:
        pdf = RawPdf(fp, "1.7")
        helv = pdf.obj(std_font("Helvetica-Bold"))
        # Font 1: uncolored stroke glyphs (d1)
        procs, diffs, widths = {}, [32, "space"], []
        procs["space"] = pdf.stream(b"800 0 0 0 0 0 d1", compress=False)
        glyph_codes = {}
        for i, d in enumerate(_DIGITS):
            name = f"digit{i}"
            procs[name] = pdf.stream(_stroke_glyph([_SEG[s] for s in d]), compress=False)
            glyph_codes[48 + i] = name
        for ch, paths in _STROKE_LETTERS.items():
            procs[ch] = pdf.stream(_stroke_glyph(paths), compress=False)
            glyph_codes[ord(ch)] = ch
        for code in range(33, 91):
            widths.append(800 if code in glyph_codes else 0)
        diffs = [32, "space"]
        for code in sorted(glyph_codes):
            diffs += [code, glyph_codes[code]]
        widths = [800] + widths
        stroke_font = pdf.obj({"Type": "Font", "Subtype": "Type3",
                               "FontBBox": [-60, -60, 660, 1060],
                               "FontMatrix": [0.001, 0, 0, 0.001, 0, 0], "CharProcs": procs,
                               "Encoding": {"Type": "Encoding", "Differences": diffs},
                               "FirstChar": 32, "LastChar": 90, "Widths": widths,
                               "Resources": {}})
        # Font 2: colored glyphs (d0), glyph space 0..100, uses a shading resource
        shading = pdf.obj({"ShadingType": 2, "ColorSpace": "DeviceRGB", "Coords": [0, 0, 100, 100],
                           "Function": {"FunctionType": 2, "Domain": [0, 1], "C0": [1, 0.8, 0],
                                        "C1": [0.6, 0, 0.8], "N": 1}, "Extend": [True, True]})
        k = 0.5523 * 45
        circle = (f"95 50 m 95 {50 + k:.2f} {50 + k:.2f} 95 50 95 c {50 - k:.2f} 95 5 {50 + k:.2f} 5 50 c "
                  f"5 {50 - k:.2f} {50 - k:.2f} 5 50 5 c {50 + k:.2f} 5 95 {50 - k:.2f} 95 50 c")
        cprocs = {
            "red": pdf.stream(f"110 0 d0 0.85 0.1 0.1 rg {circle} f".encode(), compress=False),
            "green": pdf.stream(b"110 0 d0 0.1 0.6 0.2 rg 0 0 0 RG 4 w 8 8 84 84 re B", compress=False),
            "blue": pdf.stream(b"110 0 d0 0.1 0.3 0.9 rg 5 5 m 95 5 l 50 95 l h f", compress=False),
            "shade": pdf.stream(b"110 0 d0 q 50 0 m 100 50 l 50 100 l 0 50 l h W n /Sh0 sh Q",
                                compress=False),
        }
        color_font = pdf.obj({"Type": "Font", "Subtype": "Type3", "FontBBox": [0, 0, 100, 100],
                              "FontMatrix": [0.01, 0, 0, 0.01, 0, 0], "CharProcs": cprocs,
                              "Encoding": {"Type": "Encoding",
                                           "Differences": [97, "red", "green", "blue", "shade"]},
                              "FirstChar": 97, "LastChar": 100, "Widths": [110, 110, 110, 110],
                              "Resources": {"Shading": {"Sh0": shading}}})
        bitmap_font, adv = _bitmap_font(pdf)
        res = {"Font": {"H": helv, "T1": stroke_font, "T2": color_font, "T3": bitmap_font}}
        pages_ref = pdf.alloc()
        page_refs = []
        W, H = 595.2756, 841.8898

        def add_page(cs: Content) -> None:
            content = pdf.stream(cs.data())
            page_refs.append(pdf.obj({"Type": "Page", "Parent": pages_ref, "MediaBox": [0, 0, W, H],
                                      "Resources": res, "Contents": content}))

        cs = Content()
        cs(f"BT /H 14 Tf 50 {num(H - 50)} Td (Type3 stroke font \\(d1, uncolored\\)) Tj ET")
        y = H - 110
        for size, color in ((26, "0 0 0"), (18, "0.8 0.1 0.1"), (12, "0.1 0.3 0.8")):
            cs(f"BT /T1 {size} Tf {color} rg {color} RG 50 {num(y)} Td (FASTPDF TYPE3 STROKE FONT) Tj ET")
            y -= size * 1.6
            cs(f"BT /T1 {size} Tf 50 {num(y)} Td (0123456789) Tj ET")
            y -= size * 1.6
        cs(f"BT /H 14 Tf 0 0 0 rg 50 {num(y - 10)} Td (Type3 colored glyphs \\(d0\\) with shading resource) Tj ET")
        y -= 90
        cs(f"BT /T2 48 Tf 50 {num(y)} Td (abcdabcd) Tj ET")
        cs(f"BT /T2 24 Tf 3 Tr 50 {num(y - 50)} Td (abcd) Tj 0 Tr (abcd) Tj ET")
        add_page(cs)

        cs = Content()
        cs(f"BT /H 14 Tf 50 {num(H - 50)} Td (Type3 bitmap font: 1-bit inline image masks \\(dvips style\\)) Tj ET")
        cs("BT /T3 9.5 Tf 12 TL 50 770 Td")
        words: list[str] = []
        for _ in range(58):
            line = ""
            while True:
                if not words:
                    words = latin_sentence(r).split()[::-1]
                cand = (line + " " + words[-1]) if line else words[-1]
                if line and sum(adv.get(ch, 0.5) for ch in cand) * 9.5 > W - 100:
                    break
                line = cand
                words.pop()
            cs(f"{pdf_lit(line.encode('ascii', 'replace'))} Tj T*")
        cs("ET")
        add_page(cs)
        simple_document(pdf, page_refs, pages_ref, title="FastPDF fixture: Type3 fonts",
                        id_seed="fonts-type3")
    return {"pages": len(page_refs)}


def fonts_text_state(out: Path, ctx: Ctx) -> dict:
    """Text render modes, spacing operators, TJ kerning and text matrices."""
    with open(out, "wb") as fp:
        pdf = RawPdf(fp, "1.7")
        fonts = {"F1": pdf.obj(std_font("Helvetica-Bold")), "F2": pdf.obj(std_font("Times-Roman")),
                 "F3": pdf.obj(std_font("Courier"))}
        res = {"Font": fonts}
        pages_ref = pdf.alloc()
        W, H = 595.2756, 841.8898
        cs = Content()
        cs(f"BT /F2 14 Tf 50 {num(H - 50)} Td (Text render modes 0-7 \\(Tr\\)) Tj ET")
        y = H - 100
        for mode in range(8):
            cs(f"q 0.2 0.4 0.8 rg 0.8 0.1 0.1 RG 1 w BT /F1 30 Tf {mode} Tr 50 {num(y)} Td "
               f"(Render mode {mode}) Tj ET")
            if mode >= 4:  # clipping modes: paint stripes through the text clip
                for i in range(0, 300, 6):
                    cs(f"0 {0.3 + (i % 30) / 60:.3f} 0 rg {50 + i} {num(y - 10)} 3 40 re f")
            cs("Q")
            y -= 46
        cs("BT /F2 12 Tf 50 420 Td 2 Tc (Character spacing 2 Tc) Tj 0 Tc ET")
        cs("BT /F2 12 Tf 50 400 Td 12 Tw (Word spacing 12 Tw applies to spaces) Tj 0 Tw ET")
        cs("BT /F2 12 Tf 50 380 Td 50 Tz (Horizontal scaling 50 Tz) Tj 150 Tz 220 0 Td (150 Tz) Tj 100 Tz ET")
        cs("BT /F2 12 Tf 50 360 Td (Rise: base ) Tj 5 Ts (superscript ) Tj -4 Ts (subscript) Tj 0 Ts ET")
        cs("BT /F2 12 Tf 16 TL 50 340 Td (TL + T* line one) Tj T* (line two via ' operator) Tj "
           "(line three) ' 3 1 (line four via \" operator) \" ET")
        cs("BT /F2 16 Tf 50 260 Td [(K) 120 (erning) -500 (T) 80 (J) -2000 (array) 1000 (W) 120 (A) 90 (V)] TJ ET")
        cs("BT /F1 20 Tf 0.866 0.5 -0.5 0.866 300 150 Tm (Rotated 30 deg) Tj ET")
        cs("BT /F1 20 Tf 1 0 0.4 1 50 150 Tm (Skewed text) Tj ET")
        cs("BT /F3 10 Tf 1 0 0 -1 50 100 Tm (Mirrored \\(negative d\\)) Tj ET")
        cs("0 0 0 1 k BT /F1 14 Tf 50 60 Td (CMYK fill) Tj 0.5 g (Gray fill) Tj 0 0.5 0 rg (RGB fill) Tj ET")
        content = pdf.stream(cs.data())
        page = pdf.obj({"Type": "Page", "Parent": pages_ref, "MediaBox": [0, 0, W, H],
                        "Resources": res, "Contents": content})
        simple_document(pdf, [page], pages_ref, title="FastPDF fixture: text state operators",
                        id_seed="fonts-text-state")
    return {"pages": 1}


def jobs() -> list[Job]:
    return [
        Job("small-text/one-page-helvetica.pdf", small_one_page, "open_ok",
            "單頁純文字（Helvetica，standard-14，未嵌入），最基本的開檔／首頁渲染基準。",
            pages=1, features=("standard-14", "reportlab"), producer="reportlab", cost=0.2),
        Job("small-text/three-pages-platypus-times.pdf", small_three_pages_platypus, "open_ok",
            "三頁 platypus 排版：Times 內文、標題、項目符號、表格、書籤（outline）、內部與外部連結。",
            pages=3, features=("standard-14", "outlines", "link-annotations", "table"),
            producer="reportlab", cost=0.3),
        Job("small-text/two-pages-courier-letter.pdf", small_two_pages_courier, "open_ok",
            "兩頁 Letter 尺寸、Courier 等寬字型的純文字 log。",
            pages=2, features=("standard-14", "monospace", "letter"), producer="reportlab", cost=0.2),
        Job("large-text/dense-300p-times.pdf", large_dense_times, "open_ok",
            "300 頁密集單欄文字（Times-Roman 9pt，每頁約 70 行），每 10 頁一個書籤。",
            pages=300, features=("standard-14", "outlines", "dense-text"), producer="reportlab",
            cost=6),
        Job("large-text/dense-300p-2col-helvetica.pdf", large_dense_two_column, "open_ok",
            "300 頁雙欄密集文字（Helvetica 8pt）＋小標題，測試文字抽取順序與大量 Tj。",
            pages=300, features=("standard-14", "two-column", "dense-text"), producer="reportlab",
            cost=6),
        Job("large-page-count/flat-2000p-reportlab.pdf", pages_flat_reportlab, "open_ok",
            "2000 頁簡單頁面（大標題＋色塊＋數行文字），扁平 page tree（單一 /Pages 含 2000 kids）。",
            pages=2000, features=("flat-page-tree", "standard-14"), producer="reportlab", cost=5),
        Job("large-page-count/balanced-tree-2000p.pdf", pages_balanced_tree, "open_ok",
            "2000 頁、fan-out 10 的平衡 page tree；MediaBox／CropBox／Rotate／Resources 皆由中間節點繼承。",
            pages=2000, features=("balanced-page-tree", "inherited-attributes", "rotate"), cost=1.5),
        Job("large-page-count/objstm-xrefstream-2000p.pdf", pages_objstm, "open_ok",
            "PDF 1.5：2000 頁的 page／pages 字典全部放在 object stream，並使用 cross-reference stream；頁面尺寸輪替。",
            pages=2000, features=("object-streams", "xref-stream", "mixed-page-sizes"), cost=1.5),
        Job("fonts/standard14-all.pdf", fonts_standard14, "open_ok",
            "全部 14 個 standard Type 1 字型（未嵌入）、WinAnsi／Symbol／ZapfDingbats／StandardEncoding 字碼表、MacRoman 與 /Differences。",
            pages=6, features=("standard-14", "WinAnsiEncoding", "MacRomanEncoding", "Differences"),
            cost=0.3),
        Job("fonts/truetype-subset-vera.pdf", fonts_truetype_vera, "open_ok",
            "嵌入 TrueType subset（reportlab 內附 Bitstream Vera 四種字重，FontFile2，每個 subset ≤256 字）。",
            pages=4, features=("TrueType", "FontFile2", "subset", "embedded"), producer="reportlab",
            cost=0.4),
        Job("fonts/type1-embedded-callig15.pdf", fonts_type1_embedded, "open_ok",
            "嵌入 Type 1 字型程式（FontFile，reportlab 內附 callig15，授權允許自由散布）。",
            pages=1, features=("Type1", "FontFile", "embedded"), producer="reportlab", cost=0.2),
        Job("fonts/type3-vector-and-bitmap.pdf", fonts_type3, "open_ok",
            "Type3 字型：d1 無色筆畫字、d0 彩色字（含 shading 資源）、以及 dvips 風格 1-bit inline image mask 點陣字（大量 glyph）。",
            pages=2, features=("Type3", "d0", "d1", "inline-image", "ImageMask"), cost=0.4),
        Job("fonts/text-state-operators.pdf", fonts_text_state, "open_ok",
            "文字狀態運算子：Tr 0–7（含 clip 模式）、Tc、Tw、Tz、Ts、TL、T*、' 與 \"、TJ kerning、旋轉／斜切／鏡像 Tm。",
            pages=1, features=("text-render-modes", "TJ", "Tm"), cost=0.1),
    ]
