#!/usr/bin/env python3
"""Generate THIRD_PARTY_LICENSES.md from `cargo metadata` (spec §36, §37).

Walks the resolved dependency graph of the workspace members (normal and
build dependencies; dev-dependencies are excluded because they never ship)
and lists every third-party crate with its license. Licenses outside the
permissive allowlist are flagged for manual review.

Usage:
    python tools/license_report.py [--features "a,b"] [--all-features]
                                   [--target TRIPLE] [--out THIRD_PARTY_LICENSES.md] [--check]

--check exits with status 1 when a crate needs review, for CI.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# SPDX identifiers acceptable without review for a commercial, closed-or-open
# distribution (attribution obligations still apply and are listed below).
PERMISSIVE = {
    "MIT", "MIT-0", "Apache-2.0", "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause", "BSD-3-Clause", "0BSD", "ISC", "Zlib", "BSL-1.0",
    "CC0-1.0", "Unlicense", "Unicode-3.0", "Unicode-DFS-2016", "bzip2-1.0.6",
}
# Need a human decision before shipping (copyleft or unusual terms).
REVIEW_HINTS = {
    "MPL-2.0": "weak copyleft (file-level): modified MPL files must stay MPL",
    "LGPL": "LGPL: static linking in Rust makes compliance hard; avoid",
    "GPL": "GPL: incompatible with closed-source distribution; avoid",
    "AGPL": "AGPL: avoid",
    "OFL-1.1": "font license: fine for bundled fonts, not for code",
    "OpenSSL": "OpenSSL/SSLeay terms: advertising clause",
}


def cargo_metadata(features: str | None, all_features: bool, target: str) -> dict:
    cmd = ["cargo", "metadata", "--format-version", "1", "--locked", "--filter-platform", target]
    if all_features:
        cmd.append("--all-features")
    elif features:
        cmd += ["--features", features]
    out = subprocess.run(cmd, cwd=ROOT, check=True, capture_output=True)
    return json.loads(out.stdout)


def shipped_packages(meta: dict) -> list[dict]:
    """Packages reachable from workspace members via non-dev edges."""
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    packages = {p["id"]: p for p in meta["packages"]}
    members = set(meta["workspace_members"])
    seen: set[str] = set()
    stack = list(members)
    while stack:
        pid = stack.pop()
        if pid in seen:
            continue
        seen.add(pid)
        for dep in nodes[pid]["deps"]:
            kinds = {k.get("kind") for k in dep["dep_kinds"]}
            if kinds - {"dev"}:
                stack.append(dep["pkg"])
    return sorted(
        (packages[p] for p in seen - members),
        key=lambda p: (p["name"], p["version"]),
    )


def classify(license_expr: str | None) -> tuple[bool, str]:
    """Returns (needs_review, note)."""
    if not license_expr:
        return True, "no license metadata"
    expr = license_expr.replace("/", " OR ")
    # An OR-expression is fine if any alternative is fully permissive.
    for alternative in re.split(r"\s+OR\s+", expr):
        terms = [t.strip("() ") for t in re.split(r"\s+AND\s+", alternative)]
        if all(t in PERMISSIVE for t in terms if t):
            return False, ""
    for key, hint in REVIEW_HINTS.items():
        if key in expr:
            return True, hint
    return True, "not in the permissive allowlist"


def render(packages: list[dict], args: argparse.Namespace) -> tuple[str, int]:
    review = []
    rows = []
    for p in packages:
        needs, note = classify(p.get("license"))
        repo = p.get("repository") or ""
        rows.append(f"| {p['name']} | {p['version']} | {p.get('license') or '—'} | {repo} |")
        if needs:
            review.append(f"| {p['name']} | {p['version']} | {p.get('license') or '—'} | {note} |")
    feature_note = "all features" if args.all_features else (args.features or "default features")
    lines = [
        "# Third-Party Licenses",
        "",
        "<!-- Generated by tools/license_report.py — do not edit by hand. -->",
        "",
        f"Dependency graph: workspace members, {feature_note}, target `{args.target}`, "
        "normal + build dependencies "
        "(dev-dependencies excluded). Regenerate after every dependency change "
        "(spec §36–§37).",
        "",
        "## Needs review",
        "",
    ]
    if review:
        lines += ["| Crate | Version | License | Note |", "|---|---|---|---|", *review]
    else:
        lines.append("None — every shipped crate has a permissive license option.")
    lines += [
        "",
        "## Attribution obligations",
        "",
        "- Apache-2.0 crates: ship the license text and any `NOTICE` file contents with the binary.",
        "- MIT / BSD / ISC / Zlib crates: ship the copyright notice and license text.",
        "- Code copied or ported from upstream projects (e.g. pdf-reader-gpui, Apache-2.0) must keep",
        "  its copyright header and be listed in the section below.",
        "",
        "## Ported source",
        "",
        "None yet.",
        "",
        f"## All shipped crates ({len(packages)})",
        "",
        "| Crate | Version | License | Repository |",
        "|---|---|---|---|",
        *rows,
        "",
    ]
    return "\n".join(lines), len(review)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--features")
    parser.add_argument("--all-features", action="store_true")
    parser.add_argument("--target", default="x86_64-pc-windows-msvc",
                        help="only count dependencies used on this target (Windows-first)")
    parser.add_argument("--out", type=Path, default=ROOT / "THIRD_PARTY_LICENSES.md")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text, review_count = render(shipped_packages(cargo_metadata(args.features, args.all_features, args.target)), args)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({review_count} crate(s) need review)")
    return 1 if args.check and review_count else 0


if __name__ == "__main__":
    sys.exit(main())
